<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $ticket->number }} — {{ $ticket->subject }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1e293b; line-height: 1.5; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        h2 { font-size: 14px; margin: 24px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
        .meta { color: #64748b; font-size: 11px; margin-bottom: 16px; }
        .grid { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        .grid td { padding: 4px 8px 4px 0; vertical-align: top; }
        .grid .label { color: #64748b; width: 120px; }
        .message { border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px; margin-bottom: 10px; page-break-inside: avoid; }
        .message-header { font-size: 11px; color: #64748b; margin-bottom: 6px; }
        .message-body { white-space: pre-wrap; }
        .internal { background: #fef9c3; border-color: #fde047; }
        .lifecycle-item { padding: 6px 0; border-bottom: 1px solid #f1f5f9; }
        .lifecycle-time { color: #94a3b8; font-size: 10px; }
        .footer { margin-top: 24px; font-size: 10px; color: #94a3b8; }
    </style>
</head>
<body>
    <h1>{{ $ticket->number }}</h1>
    <p class="meta">Exported {{ $exportedAt }}</p>

    <h2>Details</h2>
    <table class="grid">
        <tr>
            <td class="label">Subject</td>
            <td>{{ $ticket->subject }}</td>
        </tr>
        <tr>
            <td class="label">Status</td>
            <td>{{ $ticket->status?->name ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Priority</td>
            <td>{{ $ticket->priority?->name ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Contact</td>
            <td>{{ $ticket->contact?->name ?? $ticket->contact?->email ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Assignee</td>
            <td>{{ $ticket->assignee?->name ?? 'Unassigned' }}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td>{{ $ticket->department?->name ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Team</td>
            <td>{{ $ticket->team?->name ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Created</td>
            <td>{{ $ticket->created_at?->format('M j, Y g:i A') }}</td>
        </tr>
    </table>

    @if($ticket->description)
        <h2>Description</h2>
        <p style="white-space: pre-wrap;">{{ $ticket->description }}</p>
    @endif

    <h2>Lifecycle</h2>
    @forelse($lifecycle as $entry)
        <div class="lifecycle-item">
            <div>{{ $entry['description'] }}</div>
            <div class="lifecycle-time">{{ $entry['actor'] }} · {{ \Illuminate\Support\Carbon::parse($entry['created_at'])->format('M j, Y g:i A') }}</div>
        </div>
    @empty
        <p class="meta">No lifecycle events recorded.</p>
    @endforelse

    @if($includeConversation && count($messages) > 0)
        <h2>Conversation</h2>
        @foreach($messages as $message)
            <div class="message {{ $message['is_internal'] ? 'internal' : '' }}">
                <div class="message-header">
                    {{ $message['author'] }}
                    @if($message['is_internal']) (Internal note) @endif
                    · {{ $message['created_at'] }}
                </div>
                <div class="message-body">{{ $message['body'] }}</div>
            </div>
        @endforeach
    @endif

    <p class="footer">Generated by {{ config('app.name') }}</p>
</body>
</html>
