<?php

return array (
  'capability' => 'Capability',
  'common_questions' => 'Common questions',
  'why_teams_switch' => 'Why teams switch',
  'faq' => 'FAQ',
  'explore_product' => 'Explore product',
  'shared_inbox' => 'Shared inbox',
  'live_chat' => 'Live chat',
  'analytics' => 'Analytics',
  'features' => 'Features',
  'migrate_nav' => 'Migration guides',
  'migrate_compare_link' => 'Compare vs {name}',
  'migrate_steps_title' => 'Migration in four phases',
  'migrate_steps_subtitle' => 'Most teams run {brand} parallel to their current helpdesk for one to two weeks before cutover.',
  'migrate_checklist_title' => 'Pre-cutover checklist',
  'compare_nav' => 'Compare',
  'compare_detailed_pages' => 'See detailed competitor comparisons',
  'feature_landing_links' => 'Explore dedicated feature pages',
  'explore_product_features' => 'Explore product features',
  'social_proof_logos' => 
  array (
    0 => 'E-commerce',
    1 => 'SaaS',
    2 => 'Agencies',
    3 => 'IT & ops',
    4 => 'Professional services',
  ),
  'view_pricing' => 'View pricing',
  'feature_comparison' => 'Feature comparison',
  'compare_disclaimer' => 'Comparison based on publicly available product information. Competitor plans and packaging change — verify current details on their websites.',
  'compare_why_switch_title' => 'Why teams switch from {competitor}',
  'skip_to_main_content' => 'Skip to main content',
  'learn_more' => 'Learn more',
  'layout' => 
  array (
    'product' => 'Product',
    'ai' => 'AI',
    'features' => 'Features',
    'how_it_works' => 'How it works',
    'pricing' => 'Pricing',
    'faq' => 'FAQ',
    'sign_in' => 'Sign in',
    'start_free_trial' => 'Start free trial',
    'footer_tagline' => 'AI-powered helpdesk and ITSM for growing teams — unified inbox, live chat, knowledge base, automation, and optional Service Desk in one platform.',
    'footer_product' => 'Product',
    'footer_features' => 'Features',
    'footer_solutions' => 'Solutions',
    'footer_company' => 'Company',
    'footer_compare' => 'Compare',
    'footer_migrate' => 'Migrate',
    'footer_platform_overview' => 'Platform overview',
    'footer_get_started' => 'Get started',
    'footer_sign_in_workspace' => 'Sign in to workspace',
    'footer_platform_admin' => 'Platform admin',
    'footer_setup_guide' => 'Setup guide',
    'footer_capabilities' => 'Capabilities',
    'footer_capability_inbox' => 'Shared inbox & agent workspace',
    'footer_capability_channels' => 'Live chat, SMS & portal',
    'footer_capability_kb' => 'Knowledge base & service catalog',
    'footer_capability_sla' => 'SLA, automation & AI deflection',
    'footer_capability_service_desk' => 'Service Desk ITSM (add-on)',
    'footer_capability_integrations' => 'Integrations, SSO & asset CMDB',
    'footer_rights' => 'All rights reserved.',
    'footer_product_of' => 'A product of',
    'footer_hosted' => 'Cloud-hosted · Dedicated workspace · Custom domain on Enterprise',
    'why_us' => 'Why us',
  ),
  'blog' => 
  array (
    'index_nav_label' => 'Blog',
    'index_title' => 'Helpefi Blog',
    'index_subtitle' => 'Guides on AI helpdesk software, ticket management, ITSM, and customer support best practices.',
    'empty_state' => 'New articles coming soon.',
    'continue_exploring' => 'Continue exploring',
    'cta_title' => 'Put these ideas into practice',
    'cta_body' => 'Start your {days}-day free trial and launch an AI-powered helpdesk today.',
  ),
);
