<?php

return [
    'queue' => env('PLATFORM_AUDIT_QUEUE', 'default'),
    'queue_connection' => env('PLATFORM_AUDIT_QUEUE_CONNECTION', 'central'),

    'events' => [
        'platform.auth.login' => 'Platform admin signed in',
        'platform.auth.login_failed' => 'Platform sign-in failed',
        'platform.auth.logout' => 'Platform admin signed out',
        'platform.tenant.updated' => 'Workspace updated',
        'platform.tenant.blocked' => 'Workspace blocked',
        'platform.tenant.unblocked' => 'Workspace unblocked',
        'platform.tenant.plan_changed' => 'Workspace plan changed',
        'platform.tenant.infrastructure_updated' => 'Workspace infrastructure updated',
        'platform.tenant.infrastructure_verified' => 'Workspace infrastructure verified',
        'platform.tenant.infrastructure_failed' => 'Workspace infrastructure failed',
        'platform.tenant.infrastructure_database_migrated' => 'Workspace database migrated to external',
        'platform.tenant.infrastructure_storage_migrated' => 'Workspace storage migrated to external',
        'platform.tenant.infrastructure_migration_failed' => 'Workspace infrastructure migration failed',
        'platform.tenant.infrastructure_backup_exported' => 'Workspace database exported to customer bucket',
        'platform.tenant.infrastructure_migration_pending' => 'Workspace has pending tenant migrations',
        'platform.tenant.byo_allowed' => 'Workspace BYO allowlist enabled',
        'platform.tenant.byo_disallowed' => 'Workspace BYO allowlist disabled',
        'platform.registration.deleted' => 'Pending registration removed',
        'platform.registrations.purged_expired' => 'Expired pending registrations purged',
        'platform.user.created' => 'Platform user created',
        'platform.user.updated' => 'Platform user updated',
        'platform.user.deleted' => 'Platform user deleted',
        'platform.role.created' => 'Platform role created',
        'platform.role.updated' => 'Platform role updated',
        'platform.role.deleted' => 'Platform role deleted',
        'platform.settings.updated' => 'Platform settings updated',
        'platform.email_template.created' => 'Email template created',
        'platform.email_template.updated' => 'Email template updated',
        'platform.email_template.deleted' => 'Email template deleted',
        'platform.blog_post.created' => 'Marketing blog post created',
        'platform.blog_post.updated' => 'Marketing blog post updated',
        'platform.blog_post.deleted' => 'Marketing blog post deleted',
        'platform.testimonial.created' => 'Homepage testimonial created',
        'platform.testimonial.updated' => 'Homepage testimonial updated',
        'platform.testimonial.deleted' => 'Homepage testimonial deleted',
        'platform.testimonials.visibility_updated' => 'Homepage testimonials visibility updated',
        'platform.backup.schedule_updated' => 'Backup schedule updated',
        'platform.backup.created' => 'Backup queued',
        'platform.backup.completed' => 'Backup completed',
        'platform.backup.failed' => 'Backup failed',
        'platform.backup.deleted' => 'Backup deleted',
    ],
];
